[tool.poetry]
name = "alan_transformer"
version = "0.1.0"
description = ""
authors = ["Alan <41682961+alan-cooney@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "alan_transformer"}]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.13.1"
fancy-einsum = "^0.0.3"
numpy = "^1.24.0"
einops = "^0.6.0"
typeguard = "^2.13.3"
torchtext = "^0.14.1"
torchdata = "^0.5.1"
tqdm = "^4.64.1"
transformers = "^4.25.1"
datasets = "^2.8.0"
wandb = "^0.13.9"
jaxtyping = "^0.2.14"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
autopep8 = "^2.0.1"
mypy = "^0.991"
snapshottest = "^0.6.0"
pytest-mock = "^3.10.0"
ipykernel = "^6.19.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Enable torchtyping patching of typeguard when running pytest
# [tool.pytest.ini_options]
# addopts = "--torchtyping-patch-typeguard --typeguard-packages='alan_transformer'"
